### ISSUE TITLE
Wrong os name (macosx) leads to 404 not found for 4.7 version.

### ISSUE THREAD

**Issue by akpella** [sqtran/asdf-oc#1]
As per checking in https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.0, the tar file for macos has the name "mac", but on the install file, the os name is "macosx". This leads to the error 404 when trying to run `asdf install oc 4.7.0`.

**Comment by sqtran** [comment]
Thank you for reporting the bug!  

I've pushed a new update that should take care of it.  Please let know if you're still seeing an error after updating the asdf-oc plugin via  `asdf plugin update oc`

**Comment by sqtran** [comment]
Hey @akpella  I just noticed that you changed the title of this issue to report an additional defect.  Sorry I didn't see that until now.

Could you try `asdf install oc 4.7.0` again?  Please open a new issue if it doesn't work.
